# .goreleaser.yml
project_name: agent  # 替换为你的项目名
builds:
  - main: ./cmd/agent
    goos:
      - linux
    goarch:
      - mipsle
    env:
      - CGO_ENABLED=0  # 禁用 CGO 以生成纯静态二进制文件
    ldflags:
      - -s -w  # 去掉调试信息以减小二进制文件大小
    binary: nezha-agent-mipsle  # 替换为你的二进制文件名

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - nezha-agent-mipsle  # 替换为你的二进制文件名

checksum:
  name_template: "checksums.txt"
