builds:
  - id: universal
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - mipsle
    main: ./cmd/agent
    binary: nezha-agent

universal_binaries:
  - name_template: "nezha-agent"
    replace: false

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "nezha-agent"

archives:
  - name_template: "nezha-agent_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - New translations
