name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.20

    steps:
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/agent/agent

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.13"

      - name: Install UPX
        run: |
          apt-get update
          apt-get install -y upx

      - name: Build and release with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: List build directory
        run: ls -R dist

      - name: Compress binary with UPX
        run: upx --best --ultra-brute dist/agent_linux_mipsle/agent-nezha  # 替换为实际路径
